# Generated by Django 5.2.4 on 2025-08-12 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва')),
                ('description', models.CharField(max_length=150, verbose_name='Опис')),
                ('done', models.BooleanField(default=False, verbose_name='Виконано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('doe_date', models.DateField(blank=True, null=True, verbose_name='Дата виконання')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Час виконання')),
                ('priority', models.CharField(choices=[('high', '🔴 Високий'), ('medium', '🟡 Середній'), ('low', '⚪ Низький')], default='medium', max_length=10, verbose_name='Пріоритет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='noteapp.tag', verbose_name='Теги')),
            ],
        ),
    ]
