# Generated by Django 5.2.3 on 2025-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='doe_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
