# Generated by Django 5.2.4 on 2025-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Час виконання'),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('high', '🔴 Високий'), ('medium', '🟡 Середній'), ('low', '⚪ Низький')], default='medium', max_length=10, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='note',
            name='doe_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата виконання'),
        ),
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='noteapp.tag', verbose_name='Теги'),
        ),
    ]
