# Generated by Django 5.2.4 on 2025-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва'),
        ),
    ]
