# Generated by Django 5.2.4 on 2025-09-05 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='ua',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user'], name='noteapp_pus_user_id_58b739_idx'),
        ),
    ]
