# Generated by Django 5.2.4 on 2025-10-05 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_alter_note_options_alter_note_tags_alter_note_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='note',
            name='doe_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='note',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Due time'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('high', '🔴 High'), ('medium', '🟡 Medium'), ('low', '⚪ Low')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='noteapp.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
