# Generated by Django 5.2.4 on 2025-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('stream_url', models.URLField(help_text='Прямий URL аудіо‑потоку (mp3/aac/ogg)')),
                ('website_url', models.URLField(blank=True)),
                ('icon_url', models.URLField(blank=True, help_text='Посилання на favicon/лого')),
                ('country', models.CharField(blank=True, max_length=60)),
                ('tags', models.CharField(blank=True, help_text='Через кому: news, jazz …', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
