# Generated by Django 5.2.4 on 2025-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Link to favicon/logo'),
        ),
        migrations.AlterField(
            model_name='station',
            name='stream_url',
            field=models.URLField(help_text='Direct audio stream URL (mp3/aac/ogg)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='tags',
            field=models.CharField(blank=True, help_text='Because of coma: news, jazz …', max_length=200),
        ),
    ]
