# fly.toml app configuration file generated for personal-asistant on 2025-08-01T13:49:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-asistant'
primary_region = 'arn'
console_command = '/code/manage.py shell'

[build]


[env]
PORT = '8000'
DJANGO_SETTINGS_MODULE = "personal_asistant.settings_dev"
REDIS_URL = "redis://default:1ikNX2u9Q4oAPumtRcDCwnx8pRdKz42a@redis-12925.c328.europe-west3-1.gce.redns.redis-cloud.com:12925"

USE_SQLITE = "0"
#SQLITE_PATH = "/data/db.sqlite3"

[processes]
app    = "sh -c '/entrypoint.sh'"
worker = "celery -A personal_asistant worker -l info"
beat   = "celery -A personal_asistant beat -l info"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source = "data"
  destination = "/data"

[deploy]
  release_command = "sh -c 'python manage.py migrate --noinput'"