# Generated by Django 5.2.4 on 2025-10-18 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='is_group',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='threadmember',
            name='created',
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('dm', 'Direct'), ('group', 'Group')], default='lobby', max_length=10),
        ),
        migrations.AddField(
            model_name='threadmember',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
