# Generated by Django 5.2.4 on 2025-10-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usersettings_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
