# Generated by Django 5.2.4 on 2025-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
